# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Takosuke
tagline:          'space octopie'
description:      'ramblings'
url:              http://takosuke.github.io
baseurl:          /

author:
  name:           'Mario'
  url:            https://www.takosuke.biz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/
